### ISSUE TITLE
分开处理私聊和群聊的戳一戳

### ISSUE THREAD

**Issue by ccicnce113424** [laxtiz/koishi-plugin-poke#2]
私聊戳一戳不能带at，回复的消息也无法发送at。

**Comment by laxtiz** [comment]
## 关于发送戳一戳的poke 命令在私聊中无法输入at参数

poke 命令的参数`@user`，不仅支持QQ原生at（即`<at id=123456/>`形式），也支持`@123456` 这种简写形式，这是koishi框架对于命令参数类型的规范

> user: string 用户，格式为 {platform}:{id} (调用时可以使用 at 元素或者 @{platform}:{id} 的格式)

一般来说很少有在私聊中使用poke 命令去戳另一个用户的需求，但是也可以通过`poke @123456`来完成。

**戳命令发送者本人，可以省略参数**

另外 poke 命令不建议普通用户使用，只是`koishi-adapter-onebot`适配器目前不支持戳一戳接口，我添加了一个命令方便其他插件调用，比如在本插件中使用命令模式回戳

---

## 关于响应回复消息模式在私聊中不支持发送at

本插件只是提供了插入at的能力，并不代表插件用户必须使用

经过测试，即使是默认设置里的`<at id={userId}/>`，在私聊中也不会报错，只是不显示

实际上插件用户多数情况是将消息模式作为随机命令使用，用来插入用户id

比如配合[memes-api](https://github.com/lgc-KoiDev/koishi-plugin-memes-api) 插件，消息内容可以填写`<execute>meme generate 击剑 @{userId} @{targetId}</execute>`

> 此处用到了`@123456` 这种简写形式
